package com.mdb255.wedding.domain.datamodel;

// Generated by Hibernate Tools

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rsvp generated by hbm2java
 */
@Entity
@Table(name = "rsvp", catalog = "weddingdb")
public class Rsvp implements java.io.Serializable {

	private Integer rsvpId;
	private String firstName;
	private String lastName;
	private String email;
	private boolean attdReception;
	private boolean attdBoat;
	private boolean attdNone;
	private String dinner;
	private String dessert;
	private String guestType;
	private String submitterEmail;

	public Rsvp() {
	}

	public Rsvp(String firstName, String lastName, String email,
			boolean attdReception, boolean attdBoat, boolean attdNone,
			String dinner, String dessert, String guestType,
			String submitterEmail) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.attdReception = attdReception;
		this.attdBoat = attdBoat;
		this.attdNone = attdNone;
		this.dinner = dinner;
		this.dessert = dessert;
		this.guestType = guestType;
		this.submitterEmail = submitterEmail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rsvp_id", unique = true, nullable = false)
	public Integer getRsvpId() {
		return this.rsvpId;
	}

	public void setRsvpId(Integer rsvpId) {
		this.rsvpId = rsvpId;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "attd_reception", nullable = false)
	public boolean isAttdReception() {
		return this.attdReception;
	}

	public void setAttdReception(boolean attdReception) {
		this.attdReception = attdReception;
	}

	@Column(name = "attd_boat", nullable = false)
	public boolean isAttdBoat() {
		return this.attdBoat;
	}

	public void setAttdBoat(boolean attdBoat) {
		this.attdBoat = attdBoat;
	}

	@Column(name = "attd_none", nullable = false)
	public boolean isAttdNone() {
		return this.attdNone;
	}

	public void setAttdNone(boolean attdNone) {
		this.attdNone = attdNone;
	}

	@Column(name = "dinner", nullable = false, length = 45)
	public String getDinner() {
		return this.dinner;
	}

	public void setDinner(String dinner) {
		this.dinner = dinner;
	}

	@Column(name = "dessert", nullable = false, length = 45)
	public String getDessert() {
		return this.dessert;
	}

	public void setDessert(String dessert) {
		this.dessert = dessert;
	}

	@Column(name = "guest_type", nullable = false, length = 10)
	public String getGuestType() {
		return this.guestType;
	}

	public void setGuestType(String guestType) {
		this.guestType = guestType;
	}

	@Column(name = "submitter_email", nullable = false, length = 60)
	public String getSubmitterEmail() {
		return this.submitterEmail;
	}

	public void setSubmitterEmail(String submitterEmail) {
		this.submitterEmail = submitterEmail;
	}

}
